services:
  mongodb:
    image: mongo:8.0.3
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  dbmanager:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dbmanager
    env_file: ./services/dbmanager/.env
    environment:
      - DB_HOST=mongodb
    ports:
      - 6000:6000
    depends_on:
      - mongodb

  authmanager:
    build:
      context: .
      dockerfile: .docker/Dockerfile.authmanager
    env_file: ./services/authmanager/.env
    environment:
      - DBM_HOST=dbmanager:6000
    ports:
      - 6001:6001
    depends_on:
      - dbmanager
