services:
  mongodb:
    image: mongo:8.0.3
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  dbmanager:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dbmanager
    env_file: ./services/dbmanager/.env
    environment:
      - DB_HOST=mongodb
    ports:
      - 6000:6000
    depends_on:
      - mongodb
